<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') exit;

require_once 'db.php';

$data = json_decode(file_get_contents("php://input"), true);

$payment_reference = $data['payment_reference'] ?? '';
$client_email      = $data['client_email']      ?? '';
$client_name       = $data['client_name']       ?? '';
$amount            = floatval($data['amount']    ?? 0);
$payment_date      = $data['payment_date']       ?? date('Y-m-d');
$payment_method    = $data['payment_method']     ?? '';
$loan_number       = $data['loan_number']        ?? '';
$tenant_name       = $data['tenant_name']        ?? 'MicroFin';
$tenant_id         = $data['tenant_id']          ?? '';

if (empty($payment_reference) || empty($client_email)) {
    echo json_encode(['success' => false, 'message' => 'Missing payment_reference or client_email.']);
    exit;
}

// Load PHPMailer
$phpmailerPath = __DIR__ . '/PHPMailer';
if (!file_exists("$phpmailerPath/src/PHPMailer.php")) {
    echo json_encode(['success' => false, 'message' => 'PHPMailer not available. Email not sent.']);
    exit;
}

require "$phpmailerPath/src/Exception.php";
require "$phpmailerPath/src/PHPMailer.php";
require "$phpmailerPath/src/SMTP.php";

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

// Format amount
$amountFormatted = '₱' . number_format($amount, 2);

// Build receipt HTML
$html = <<<HTML
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; background: #f8fafc; margin: 0; padding: 0; }
  .wrapper { max-width: 560px; margin: 30px auto; background: #fff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
  .header { background: #1a3c5e; padding: 32px 28px; text-align: center; }
  .header h1 { color: #fff; margin: 0; font-size: 22px; font-weight: 700; }
  .header p  { color: rgba(255,255,255,0.75); margin: 6px 0 0; font-size: 13px; }
  .badge { display: inline-block; margin-top: 16px; background: rgba(255,255,255,0.2); color: #fff;
           padding: 6px 18px; border-radius: 100px; font-size: 13px; font-weight: 700; }
  .amount-block { text-align: center; padding: 28px; border-bottom: 1px dashed #e2e8f0; }
  .amount-block .label { font-size: 12px; color: #64748b; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; }
  .amount-block .amount { font-size: 42px; font-weight: 900; color: #1a3c5e; margin: 8px 0 0; }
  .details { padding: 24px 28px; }
  .row { display: flex; justify-content: space-between; align-items: center; padding: 12px 0;
         border-bottom: 1px solid #f1f5f9; }
  .row:last-child { border-bottom: none; }
  .row .key   { font-size: 13px; color: #64748b; font-weight: 500; }
  .row .value { font-size: 13px; color: #0f172a; font-weight: 700; text-align: right; max-width: 58%; }
  .status-paid { color: #10b981; }
  .footer { background: #f8fafc; padding: 20px 28px; text-align: center; border-top: 1px solid #e2e8f0; }
  .footer p { font-size: 12px; color: #94a3b8; margin: 0; line-height: 1.6; }
</style>
</head>
<body>
<div class="wrapper">
  <div class="header">
    <h1>$tenant_name</h1>
    <p>Official Payment Receipt</p>
    <span class="badge">✓ Payment Received</span>
  </div>
  <div class="amount-block">
    <div class="label">Amount Paid</div>
    <div class="amount">$amountFormatted</div>
  </div>
  <div class="details">
    <div class="row"><span class="key">Transaction ID</span><span class="value">$payment_reference</span></div>
    <div class="row"><span class="key">Client Name</span><span class="value">$client_name</span></div>
    <div class="row"><span class="key">Loan Number</span><span class="value">$loan_number</span></div>
    <div class="row"><span class="key">Payment Date</span><span class="value">$payment_date</span></div>
    <div class="row"><span class="key">Payment Method</span><span class="value">$payment_method</span></div>
    <div class="row"><span class="key">Status</span><span class="value status-paid">✓ PAID</span></div>
  </div>
  <div class="footer">
    <p>This is an official receipt generated by $tenant_name.<br>
    Please keep this for your records. For inquiries, contact your branch.</p>
  </div>
</div>
</body>
</html>
HTML;

$mail = new PHPMailer(true);
try {
    // SMTP config — adjust to your mail server
    $mail->isSMTP();
    $mail->Host       = 'smtp.gmail.com';
    $mail->SMTPAuth   = true;
    $mail->Username   = 'noreply.microfin@gmail.com'; // replace with real sender
    $mail->Password   = 'your_app_password_here';      // replace with real password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
    $mail->Port       = 587;

    $mail->setFrom('noreply.microfin@gmail.com', $tenant_name);
    $mail->addAddress($client_email, $client_name);
    $mail->isHTML(true);
    $mail->Subject = "Payment Receipt - $payment_reference | $tenant_name";
    $mail->Body    = $html;
    $mail->AltBody = "Payment Received!\n\nTransaction ID: $payment_reference\nClient: $client_name\nAmount: $amountFormatted\nDate: $payment_date\nMethod: $payment_method\nStatus: PAID\n\nThank you, $tenant_name";

    $mail->send();
    echo json_encode(['success' => true, 'message' => "Receipt sent to $client_email"]);
} catch (Exception $e) {
    echo json_encode(['success' => false, 'message' => 'Email could not be sent: ' . $mail->ErrorInfo]);
}
?>
